# Generated by Django 3.1 on 2022-03-23 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclerent',
            name='vehicle_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclerent',
            name='vehicle_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
