# Generated by Django 3.1 on 2022-03-24 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20220323_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerent',
            name='bluebook_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
