# Generated by Django 3.1 on 2022-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_vehiclebook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerent',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
